/* Product catalogue for Sri Sai Pooja Store
 * Images are stored locally in assets/products/
 * Prices are in INR (₹). mrp is the struck-through original price.
 */
const PRODUCTS = [
  {
    id: "mariamman-lamp",
    name: "Mariamman Kamatchi Vilakku",
    desc: "Solid brass Mariamman face deepam with arch crown",
    category: "Lamps & Diyas",
    price: 649,
    mrp: 899,
    unit: "1 piece",
    rating: 4.7,
    image: "assets/products/mariamman-lamp.jpg",
    tag: "Bestseller",
  },
  {
    id: "hand-diya",
    name: "Brass Aarti Hand Diya",
    desc: "Single-wick handheld aarti diya with engraved rim",
    category: "Lamps & Diyas",
    price: 199,
    mrp: 299,
    unit: "1 piece",
    rating: 4.6,
    image: "assets/products/hand-diya.jpg",
    tag: null,
  },
  {
    id: "panch-aarti-set",
    name: "Panch Aarti Diya with Bell",
    desc: "5-wick brass aarti lamp with matching pooja bell",
    category: "Aarti Sets",
    price: 899,
    mrp: 1249,
    unit: "Set of 2",
    rating: 4.8,
    image: "assets/products/panch-aarti-set.jpg",
    tag: "Combo",
  },
  {
    id: "gajalakshmi-deepam",
    name: "Gajalakshmi Kamakshi Deepam",
    desc: "Ornate brass deepam with elephants & Lakshmi motif",
    category: "Lamps & Diyas",
    price: 1499,
    mrp: 1999,
    unit: "1 piece",
    rating: 4.9,
    image: "assets/products/gajalakshmi-deepam.jpg",
    tag: "Premium",
  },
  {
    id: "kumkum-box",
    name: "Antique Kumkum Spice Box",
    desc: "Engraved brass box with 4 cups, lid & spoon",
    category: "Kumkum & Storage",
    price: 749,
    mrp: 1099,
    unit: "1 box",
    rating: 4.5,
    image: "assets/products/kumkum-box.jpg",
    tag: null,
  },
  {
    id: "engraved-kalash",
    name: "Om Swastik Engraved Kalash",
    desc: "Hand-carved brass kalash with Om & Swastik design",
    category: "Kalash & Lota",
    price: 549,
    mrp: 799,
    unit: "1 piece",
    rating: 4.7,
    image: "assets/products/engraved-kalash.jpg",
    tag: null,
  },
  {
    id: "brass-lota",
    name: "Polished Brass Lota",
    desc: "Classic smooth-finish brass lota for daily pooja",
    category: "Kalash & Lota",
    price: 349,
    mrp: 499,
    unit: "1 piece",
    rating: 4.6,
    image: "assets/products/brass-lota.jpg",
    tag: null,
  },
  {
    id: "panchapatra-kindi",
    name: "Brass Panchapatra Kindi",
    desc: "Spouted brass kindi for sacred water rituals",
    category: "Ritual Essentials",
    price: 459,
    mrp: 649,
    unit: "1 piece",
    rating: 4.7,
    image: "assets/products/panchapatra-kindi.jpg",
    tag: null,
  },
  {
    id: "pooja-thali",
    name: "Floral Engraved Pooja Thali",
    desc: "Intricate flower-carved brass plate for aarti",
    category: "Thali & Plates",
    price: 599,
    mrp: 849,
    unit: "1 piece",
    rating: 4.8,
    image: "assets/products/pooja-thali.jpg",
    tag: "Bestseller",
  },
  {
    id: "copper-kalash",
    name: "Copper Kalash with Coconut Lid",
    desc: "Stone-studded copper kalash with leaf & coconut set",
    category: "Kalash & Lota",
    price: 1299,
    mrp: 1799,
    unit: "Full set",
    rating: 4.9,
    image: "assets/products/copper-kalash.jpg",
    tag: "Premium",
  },
  {
    id: "kumkum-holder",
    name: "4-Bowl Kumkum Holder",
    desc: "Brass haldi-kumkum stand with carry handle",
    category: "Kumkum & Storage",
    price: 399,
    mrp: 549,
    unit: "1 piece",
    rating: 4.5,
    image: "assets/products/kumkum-holder.jpg",
    tag: null,
  },
  {
    id: "camphor-holder",
    name: "Karpura Camphor Aarti Holder",
    desc: "Engraved brass camphor burner with long handle",
    category: "Aarti Sets",
    price: 329,
    mrp: 449,
    unit: "1 piece",
    rating: 4.6,
    image: "assets/products/camphor-holder.jpg",
    tag: null,
  },
  {
    id: "panchapatra-set",
    name: "Copper Panchapatra & Uddharani Set",
    desc: "Achamana copper glass with spoon for daily ritual",
    category: "Ritual Essentials",
    price: 429,
    mrp: 599,
    unit: "Set of 2",
    rating: 4.7,
    image: "assets/products/panchapatra-set.jpg",
    tag: "Combo",
  },
];

const CATEGORIES = [
  { name: "All", icon: "🪔" },
  { name: "Lamps & Diyas", icon: "🪔" },
  { name: "Aarti Sets", icon: "🔔" },
  { name: "Kalash & Lota", icon: "⚱️" },
  { name: "Thali & Plates", icon: "🍽️" },
  { name: "Kumkum & Storage", icon: "🧡" },
  { name: "Ritual Essentials", icon: "🙏" },
];
